[DEFAULT]
;size of the bins to segment generated and dataset images into, or None to do no binning
BIN_SIZE = 10000 

### dataset parameters ###
;subdirectory for the Vicanek Martinez et al. 2024 cutouts
VM_DATASET_SUBDIR = dataset
;how many fits images from the VM dataset to convert, or None to convert all
VM_FITS_COUNT_CUTOFF = None

### generation parameters ###
;subdirectory to save generated images to
GENERATED_SUBDIR = generated
;batch size for image generation, to avoid OOM errors
BATCH_SIZE = 100
;number of timesteps to use in image generation
TIMESTEPS = 25
;whether or not to use the CPU for image generation instead of attempting to use CUDA
USE_CPU = False
;the number of samples to generate
N_SAMPLES = 10000
;whether or not to preserve image values on generation. If false images are scaled 0-1
PRESERVE_VALUES = True
;the name of the model to use to generate the images, as stored in model_results/<NAME>_model/parameters_<NAME>_model.pt and the associated config
MODEL_NAME = LOFAR
;the distribution of peak fluxes of the generated images, one of dataset, loguniform, or uniform
DISTRIBUTION = dataset
;upper bound of peak flux (Jy/beam) for uniform/loguniform generation
UPPER_BOUND = 0
;lower bound of peak flux (Jy/beam) for uniform/loguniform generation
LOWER_BOUND = 0

### completeness correction parameters ###
;the name(s) of the datasets(s) to use to estimate the completeness correction, comma separated
COMPLETENESS_DATASET_NAMES = generated_loguinform,generated_datadist
;the sigma threshold to use for the detection criteria, in units of the local noise
DETECTION_SIGMA_THRESHOLD = 5
;the number of flux bins to use in estimating the completeness correction
COMPLETENESS_FLUX_BINS = 25
;the number of noise patches to apply to each dataset image to estimate the completeness correction
N_NOISE_PATCHES = 5

### radio luminosity function parameters ###
;lowercase h, where the hubble constant today is H_0 = h * 100 km/(s*MPc)
h = 0.67
;temperature of the CMB today, in kelvin
Tcmb0 = 2.275
;matter density of the universe today
Om0 = 0.3
;redshift bin size
dz = 0.2
;luminosity bin count
LUM_BINS = 100
;number of points to use in the interpolation approximation of comoving volume to redshift
N_INTERP_PTS = 50
;number of mock points to generate to estimate integral across luminosity-redshift bin using monte carlo
N_MC_PTS = 1000


[dataset_distribution]
GENERATED_SUBDIR = generated_datadist
N_SAMPLES = 50000
DISTRIBUTION = dataset

[loguniform_distribution]
GENERATED_SUBDIR = generated_loguniform
N_SAMPLES = 100000
UPPER_BOUND = 1e1
LOWER_BOUND = 1e-7
DISTRIBUTION = loguniform

[uniform_distribution]
GENERATED_SUBDIR = generated_uniform
N_SAMPLES = 100000
UPPER_BOUND = 1e1
LOWER_BOUND = 1e-7
DISTRIBUTION = uniform


[no_gpu]
USE_CPU = True
BATCH_SIZE = 1
VM_FITS_COUNT_CUTOFF = 10
N_SAMPLES = 5